package io.panda.domain.model.workflow;

public enum BlockerType {
    MISSING_TICKET_INFORMATION,
    NOT_ELIGIBLE,
    MISSING_REPOSITORY_MAPPING,
    MISSING_TECHNICAL_FEEDBACK_CONTEXT,
    WAITING_TECHNICAL_REVIEW,
    WAITING_BUSINESS_FEEDBACK,
    NO_EXECUTION_ENVIRONMENT
}
