package io.devflow.domain.workflow;

public enum WorkflowAuditType {
    AGENT_RUN_ENQUEUED,
    AGENT_RUN_CANCEL_ENQUEUED,
    AGENT_RUN_STARTED,
    AGENT_PROGRESS_REPORTED,
    WORKFLOW_INPUT_REQUIRED,
    AGENT_RUN_COMPLETED,
    AGENT_RUN_FAILED,
    AGENT_RUN_CANCELLED,
    WORK_ITEM_COMMENT_REQUESTED,
    WORK_ITEM_TRANSITION_REQUESTED,
    WORK_ITEM_NOT_ELIGIBLE,
    WORK_ITEM_INCOMPLETE,
    WORK_ITEM_READY_FOR_INFORMATION_COLLECTION,
    WORK_ITEM_COMMENT_NEW,
    WORK_ITEM_COMMENT_UPDATED,
    WORK_ITEM_STATUS_CHANGED,
    CODE_CHANGE_REVIEW_COMMENT_NEW,
    CODE_CHANGE_REVIEW_COMMENT_UPDATED,
    CODE_CHANGE_MERGED,
    CODE_CHANGE_CLOSED_UNMERGED,
    DEPLOYMENT_AVAILABLE,
    BUSINESS_VALIDATION_REPORTED,
    RECONCILIATION_REQUESTED,
    MANUAL_RESUME_REQUESTED,
    MANUAL_CANCEL_REQUESTED
}
