package io.devflow.domain.workflow;

public enum WorkflowSignalType {
    WORK_ITEM_DISCOVERED,
    WORK_ITEM_UPDATED,
    WORK_ITEM_COMMENT_RECEIVED,
    WORK_ITEM_STATUS_CHANGED,
    CODE_CHANGE_REVIEW_COMMENT_RECEIVED,
    CODE_CHANGE_MERGED,
    CODE_CHANGE_CLOSED_UNMERGED,
    DEPLOYMENT_AVAILABLE,
    BUSINESS_VALIDATION_REPORTED,
    RECONCILIATION_REQUESTED,
    MANUAL_RESUME_REQUESTED,
    MANUAL_CANCEL_REQUESTED
}
